name: Publish
on:
  release:
    types: [published]

jobs:
  release:
    name: Release
    strategy:
      matrix:
        kind: ['linux', 'windows']
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
          - kind: windows
            os: windows-latest
            target: win-x64
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x

      - name: Publish Application
        run: dotnet publish -c Release -r ${{ matrix.target }} --self-contained true -o publish

      - name: Archive Release Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-app-${{ matrix.target }}
          path: publish/

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: publish/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
