name: Publish
on:
  release:
    types: [published]

jobs:
  release:
    name: Release
    strategy:
      matrix:
        kind: ['windows']
        include:
          - kind: windows
            os: windows-latest
            target: win-x64
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Publish Application
        run: dotnet publish -c Release -r ${{ matrix.target }} --self-contained true -o publish
      - name: Archive Release Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-app-${{ matrix.target }}
          path: publish/
          compression-level: 0  # Optional: Speeds up uploads, especially for large files

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: publish/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
