name: .NET Build, Package, and Release

on:
  release:
    types: [published]  # Runs when a new release is published

jobs:
  build:
    runs-on: windows-latest  # Force running only on Windows

    permissions:
      contents: write  # Allows writing to repository contents (includes creating/releasing assets)
      id-token: write   # Required for some authentication features

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Locate Project File
      id: project_file
      shell: pwsh
      run: |
        $project = Get-ChildItem -Path . -Filter "*.csproj" -Recurse | Select-Object -First 1
        echo "PROJECT_FILE=$($project.FullName)" >> $env:GITHUB_ENV

    - name: Build
      run: dotnet publish ${{ env.PROJECT_FILE }} -c Release -r win-x64 --self-contained false -o publish

    - name: Package Application
      run: Compress-Archive -Path publish\* -DestinationPath prograss-bar-gauge-x64.zip -Force

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: prograss-bar-gauge-x64.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
