name: .NET Build, Package, and Release

on:
  release:
    types: [published]  # Runs when a new release is published

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            target: linux-x64
          - os: windows-latest
            target: win-x64
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet publish -c Release -r ${{ matrix.target }} --self-contained false -o publish

    - name: Package Application
      shell: bash
      run: |
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          powershell Compress-Archive -Path publish\* -DestinationPath my-app-${{ matrix.target }}.zip -Force
        else
          zip -r my-app-${{ matrix.target }}.zip publish/*
        fi

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: my-app-${{ matrix.target }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
