name: .NET Build, Package, and Release

on:
  release:
    types: [published]  # Runs when a new release is published

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]  # Build on both Linux & Windows
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet publish --configuration Release --output publish --self-contained false

    - name: Package Application
      run: |
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          Compress-Archive -Path publish/* -DestinationPath my-app.zip
        else
          zip -r my-app.zip publish/*
        fi
      shell: bash

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: my-app.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
